### ISSUE TITLE
Upgrade Dolt version

### ISSUE THREAD

**Issue by ckreiling** [dolthub/driver#16]
Thank you for creating this driver! I'm having a lot of fun using Dolt and want to build an application on top of it in Go. Ideally I use embedded Dolt to avoid having a network dependency on a database, akin to using SQLite.

I noticed that the version of Dolt pinned in this driver is set to v0.45 which was released ~2 years ago; is there any way to upgrade it to a more recent version, perhaps the latest?

I considered pinning the dependency from within my project, however I'm having trouble targeting the /go subdirectory the dolthub/dolt repo. Any guidance would be appreciated!

**Comment by zachmu** [comment]
Hi @ckreiling,

The tag is misleading. If you look at the full dependency line:

```
github.com/dolthub/dolt/go v0.40.5-0.20231206174848-7c88abef6e9f
```

You'll see it refers to a commit from Dec 2023. The issue is we once published the v0.40.5 tag on the main branch in such a way that any time we `go get` directly against the main branch (which is what we did here) the tag shows up as v0.40.5, instead of the current release. I believe this is disruptive to fix, but I'll raise the issue again with the team and see if there's anything we can do here, since people do notice and get confused by it.

We keep the Dolt dependency up to date on about this schedule.
